INSERT INTO capacity (name,level,description,sub_class_id)
	VALUES
	('Controle des flammes',1,'Manipule l''intensité d''une flamme visible',1),
	('Projection de flamme',2,'Projette une flamme depuis la main du lanceur',1),
	('Mur de feu',4,'Concentre une flamme proche pour créer une barrière face au lanceur',1),
	('Embrasement',5,'Crée une flamme dans une zone visible par le lanceur',1),
	('Déflagration',6,'Projette un cône de flamme en continu face au lanceur',1),
	('Dôme de flammes',7,'Crée un dome de flammes protecteur autour du lanceur',1),
	('Sphère de feu',8,'Lance une boule de feu de 3m de diamètre qui explose sur commande',1),
	('Elémentaire de feu',9,'Invoque un élémentaire de feu',1),
	('Tempête de flammes',10,'Crée une immense vague de flammes se dirigeant vers l''ennemi',1),
	('Fluidité',1,'Manipule une petite quantité de liquide',2),
	('Cryothermie',2,'Altère l''état des liquide (vapeur, glace)',2),
	('Fouet aqueu',3,'Transforme un jet d''eau en une arme mortelle',2),
	('Mur de glace',4,'Transforme une zone d''eau en une paroi de glace protectrice',2),
	('Couteau de glace',5,'Lance une pointe de glace',2),
	('Cône de froid',6,'Projette un cône de givre en continu face au lanceur',2),
	('Piège givrant',7,'Crée un piège condamnant l''ennemi dans un cercueil de glace',2),
	('Elémentaire de glace',9,'Invoque un élémentaire de glace',2),
	('Raz-de-marée',10,'Provoque une vague gigantesque',2),
	('Souffle',1,'Manipule l''intensité des courants d''air',3),
	('Bourrasque',3,'Envoie une rafale de vent qui renverse les ennemis sur son passage',3),
	('Répulsion',4,'Crèe un courant d''air autour du lanceur qui projette tout ce qui se trouve aux alentours',3),
	('Ruée aérienne',5,'Le vent est du coté du lanceur et accélère ses mouvements',3),
	('Catapulte',6,'Crée une surface piégée qui projette l''ennemi en l''air',3),
	('Zone de vide',7,'Enferme l''ennemi dans une zone qui peut être vidée de son air',3),
	('Lévitation',8,'Place quelqu''un ou quelque chose en état de lévitation',3),
	('Elémentaire d''air',9,'Invoque un élémentaire d''air',3),
	('Cyclone',10,'Crée une tornade destructrice controlée par le lanceur',3),
	('Terraformation',1,'Le lanceur peur modeler la terre en contact autour de lui',4),
	('Marteau de pierre',2,'Consolide la terre pour créer une arme contondante',4),
	('Tremblement',3,'Crée un tremblement dans le sol autour du lanceur',4),
	('Peau de pierre',4,'Au contact de la pierre, la cible peut s''en recouvrir afin de se protèger',4),
	('Eruption',5,'Eruption de roche et de terre qui éclate en un point visible par le lanceur',4),
	('Pétrification',7,'Transforme la cible en statue de pierre',4),
	('Crevasse',8,'Crée une fissure dans le sol face au lanceur',4),
	('Elémentaire de pierre',10,'Invoque un élémentaire de pierre',4),
	('Météor',10,'Crée un immense amas de pierres en hauteur s''écrasant sur une zone ciblée',5),
	('Projectile magique',1,'Un projectile infligeant des dégats magiques',5),
	('Bouclier magique',2,'Invoque un bouclier magique dans la main du lanceur',5),
	('Arme liée',3,'Invoque une arme magique dans la main du lanceur',5),
	('Pénétration psychique',4,'Pénètre les pensées superficielles d''une créature à portée de main',5),
	('Maitrise arcanique',5,'Les sorts de bouclier magiques, arme liée et pénétration psychique peuvent être lancé à distance',5),
	('Télékinésie',6,'Déplace un objet où une créature légère par la pensée',5),
	('Dôme de lames',7,'Crée un dôme protecteur hérissé de lames autour du lanceur',5),
	('Téléportation',8,'Le lanceur se déplace instantanément vers un point visible',5),
	('Champ anti-magie',9,'Crée une zone à portée dans laquel la magie ne peut opérer',5),
	('Prédiction',1,'Prévois les changements météorologiques à venir',6),
	('Nappe de brouillard',3,'Étend une nappe de brouillard dans une zone',6),
	('Éclat du soleil',9,'Crée une vague magique face au lanceur qui provoque un état aléatoire à toute créature se trouvant dans la zone',6),
	('Contrôle du climat',13,'Modifie progressivement les conditions climatiques en extérieur (précipitation, température et force du vent)',6),
	('Appel de la foudre',19,'Les créatures prisent dans la zone de l''orage sont frappées par la foudre',6),
	('Communication avec les animaux',1,'Permet de dialoguer avec un animal',7),
	('Sens Animal',7,'Le lanceur peut voir/entendre/sentir à travers les sens d''une bête consentante',7),
	('Communication télépathique',11,'Communiquer télépatiquement avec les animaux',7),
	('Localisation d''animaux ou de plantes',15,'En vous concentrant sur les murmures de la Nature qui vous environne, vous apprenez la direction et la distance de la créature, ou plante que vous connaissez dans les alentours',7),
	('Domination de bête',19,'Vous tentez de prendre le contrôle d''une bête à portée que vous pouvez voir',7),
	('Interactions naturelles',1,'Permet d''influencer légèrement la végétation',8),
	('Fouet épineux',3,'Le lanceur crée une longue et épaisse liane de vignes et d''épines dans sa main',8),
	('Enchevêtrement',5,'Parralyser une créature grace à la pouse de plantes et de racines',8),
	('Nuage toxique',11,'Grâce à la pousse de champignons, un nuage toxique se propage dans une zone définie',8),
	('Colère de la foret',17,'Permet de déchaîner la colère des arbres afin qu''ils soutiennent le lanceur',8),
	('Soin léger',1,'Permet de soigner les blessures légère',9),
	('Detection de magie',5,'Le lanceur détecte toutes émanations magiques autour de lui',9),
	('Guérison',9,'Le lanceur peut soigner une altération d''état',9),
	('Armure spirituelle',15,'Crée une armure spirituelle autour du lanceur',9),
	('Prière de Sylvanna',17,'Le lanceur fait une prière à la déesse Sylvanna, peut etre l''exaucera-t-elle',9),
	('Carquoi magique',9,'Un carquoi qui ne se vide jamais',10),
	('Bombe fumigène',3,'Vous vous dissimulez derrière un écran de fumée',10),
	('Bola',5,'Lancez des bolas sur vos adversaires pour les faire chuter',10),
	('Flèche de feu',7,'Vous maitrisez le tir de flèches enflammées',10),
	('Flèche empoisonnée',9,'Empoisonnez vos flèches',10),
	('Force flèche',11,'Vos flèche peuvent transpercer un mur de pierre d''une certaine épaisseur ou le corp d''un ennemis',10),
	('Double flèche',17,'Tirez deux flèches à la fois',10),
	('Volée de flèches',19,'Toute la zone est frappée par une pluie de flèches',10),
	('Analyse de l''environnement',1,'Vous avez accès à certaines informations spécifiques à l''environnement dans lequel vous vous trouvez',11),
	('Hâte',5,'Faite +1d4 à votre jet d''initiative',11),
	('Sang-froid',9,'Vous résistez au charme et à la peur',11),
	('Camouflage',13,'Vous vous fondez dans l''environnement et devenez invisible aux yeux des ennemis jusqu''à ce que vous soyez découvert ou que vous entriez en mouvement',11),
	('Imprenable',17,'Vous ne pouvez plus être entravé ou agrippé',11),
	('Lien avec un familier',1,'Vous vous lié d''amitié avec une creature de votre choix',12),
	('Communication avec un familier',3,'Vous pouvez communiquer avec votre familier par la pensée',12),
	('Appel de familier',7,'Téléporte votre familier à vos côté',12),
	('Transfert de vie',11,'Puisez l''energie de votre familier afin de remettre sur pied un membre de votre groupe ou vous-même. Le familier est assomé',12),
	('Flèche de transfert',15,'Tirez une flèche qui, à tout moment souhaité, peut être remplacé par votre familier',12),
	('Transfert de l''âme',19,'Prenez instantanément la place de votre familer',12),
	('Provocation',1,'Force les ennemis à se retourner dans votre direction',13),
	('Force du boucher',3,'Vous frappez suffisament fort pour arracher ou découper des membres',13),
	('Attaque éclair',5,'Si vous frappez un ennemi vous avez une chance de frapper un deuxième tout prêt',13),
	('Bélier',7,'Foncez sur un groupe d''ennemis et mettez les à terre',13),
	('Retour à l''envoyeur',9,'Vous pouvez essayer de renvoyer un projectil à celui qui vous l''a lancé',13),
	('Bon du guerrier',11,'Sautez jusqu''à un ennemi pour lui tomber dessus',13),
	('Piétinement guerrier',13,'Frappez le sol avec votre arme afin de renverser les ennemis autour de vous',13),
	('Force du guerrier',15,'Vous pouvez soulever des objets de trois à quatre fois votre poids',13),
	('Ange gardien',17,'Vous pouvez prendre les dégats à la place d''un autre',13),
	('Enragement guerrier',19,'Tout vos coups sont des coups critiques pendant plusieures minutes, mais vous serez épuisé après ça',13),


	
	
	
	
	
	
	
	