export enum StoryEnum{

    ACOLYTE="ACOLYTE",
    CRAFTSMAN="CRAFTSMAN",
    ARTIST="ARTIST",
    CHARLATAN="CHARLATAN",
    KNIGHT="KNIGHT",
    CRIMINAL="CRIMINAL",
    STREETCHILD="STREETCHILD",
    ERMIT="ERMIT",
    HERO="HERO",
    SAILOR="SAILOR",
    NOBLE="NOBLE",
    SAGE="SAGE",
    SAVAGE="SAVAGE",
    SOLDIER="SOLDIER",
    MANHUNTER="MANHUNTER",
    MERCENARY="MERCENARY",
    CAPTIVE="CAPTIVE",
    IDIOT="IDIOT",
    TRAVELER="TRAVELER"

}