export enum SkillEnum {

    ATHLETICS="ATHLETICS",
    ACROBATICS="ACROBATICS",
    SLEIGHTOFHAND="SLEIGHTOFHAND",
    STEALTH="STEALTH",
    ARCANA="ARCANA",
    HISTORY="HISTORY",
    INVESTIGATION="INVESTIGATION",
    NATURE="NATURE",
    RELIGION="RELIGION",
    ANIMALHANDING="ANIMALHANDING",
    INSIGHT="INSIGHT",
    MEDECINE="MEDECINE",
    PERCEPTION="PERCEPTION",
    SURVIVAL="SURVIVAL",
    DECEPTION="DECEPTION",
    INTIMIDATION="INTIMIDATION",
    PERFORMANCE="PERFORMANCE",
    PERSUASION="PERSUASION"
    
}