export enum TypeEnum{

    HUMANOID='HUMANOID',
    ABERRATION='ABERRATION',
    BEAST='BEAST',
    CELESTIAL='CELESTIAL',
    CONSTRUCT='CONSTRUCT',
    DRAGON='DRAGON',
    ELEMENTAL='ELEMENTAL',
    FEY='FEY',
    FIEND='FIEND',
    GIANT='GIANT',
    MONSTROSITY='MONSTROSITY',
    OOZE='OOZE',
    PLANT='PLANT',
    UNDEAD='UNDEAD',
}